# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: $(Build.BuildId)
  containerRegistry: 'dba3f8f5d0df4cb492652988af71367c.azurecr.io'
  imageRepository: 'demo/shop-service'
  imagePullSecret: 'regcred-shop'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ACRConnection'
        repository: 'demo/shop-service'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'dev.dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'dev-myAKSCluster-dev-1573614110824'
              secretType: 'dockerRegistry'
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'ACRConnection'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'dev-myAKSCluster-dev-1573614110824'
              manifests: |
                $(Pipeline.Workspace)/manifests/serviceAccount.yml
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
                $(Pipeline.Workspace)/manifests/ingress.yml
                $(Pipeline.Workspace)/manifests/role.yml
              containers: $(containerRegistry)/$(imageRepository):$(tag)
              imagePullSecrets: $(imagePullSecret)
