apiVersion : extensions/v1beta1
kind: Deployment
metadata:
  name: shop-service 
spec:
  selector:
    matchLabels:
      # fill in the labels

  replicas: 1
  template:
    metadata:
      labels:
        # fill in the labels
        
    spec:
      containers:
        - name: shop-service
          image: dba3f8f5d0df4cb492652988af71367c.azurecr.io/demo/shop-service:v1
          ports:
          - name: http
            containerPort: 7500
      # fill in the name of the serviceAccount
      serviceAccountName:
