apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  app: microservice-demo
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: microservices.info
    http:
      paths:
      - path: /inventory-service
        backend:
          serviceName: inventory-service
          servicePort: 6500
      - path: /shop-service
        backend:
          serviceName: shop-service
          servicePort: 7500
